### ISSUE TITLE
When I close the app, it remains sending me notifications.

### ISSUE THREAD

**Issue by adamesalles** [frealgagu/archlinux.whatsapp-nativefier#1]
At least I think this is the repo of the package `whatsapp-nativefier` in AUR. If I'm wrong, just not consider this.

---
### My OS
I use ArcoLinux KDE/Budgie (I think that in a WM-only environment, forcing a closing should not cause this error, but it's not my case, unfortunately)

---

### The Issue

The problem is: I open the app, it's already logged in, and when I close to concentrate in other thing it sends me notifications as it was open (just the sound, I don't like desktop notifications). I already tried running `window.close()` in dev console, but the issue stays. I am not that good with nativefier and javascript, and this could be a problem in my machine, but, if there's a way to close (even via dev console) I would like to try and adopt.  

---

If you want packages versions, or something else, just ask. I don't have nativefier downloaded (I think), but I can download if it helps.

Thanks. (I am planning to reinstall my OS, if it solves this, I notice here.)

**Comment by elmeriniemela** [comment]
I have the same issue. Before I was using whatsapp-natifer-dark that had a systray icon i could use for killing the background process, now I can't do it anymore.

**Comment by frealgagu** [comment]
It's strange that tray icon is not working, actually the correct way to close the application completely is closing it from the tray. What DE are you using? I'm using KDE, but if you find a way to make it work in other DEs please let me know and I'll include it.

**Comment by adamesalles** [comment]
I really don't remember how I've solved this. Actually,  There's some months that I'm not on Arch anymore, for sad personal reasons.

In fact, I'd been using ArcoLinux for a short period before I have installed Arch Vanilla. Maybe it was a issue related to KDE, considering I've used dwm before of it, and (as I've said before) I think it haven't happen anymore. 

BTW, thank you for the package.

**Comment by frealgagu** [comment]
Same as #2
