### ISSUE TITLE
App doesn't fullscreen properly

### ISSUE THREAD

**Issue by PolpOnline** [frealgagu/archlinux.whatsapp-nativefier#10]
Hi, my app doesn't scale properly for some reason, if I try to enlarge its window above some point it creates these ugly bars around the UI.
I don't know if this is an upstream problem of Nativefier, but maybe it can just be fixed by adding flags to the build command.
Here's a screenshot of what happens:
![image](https://user-images.githubusercontent.com/53786619/133892008-234790db-1f98-4d2c-b0d8-f244e1fee342.png)

**Comment by frealgagu** [comment]
This app is electron based, which means it's just a wrapper of web browser. If you login via any other web browser this behaves the same, so it's not something which should be fixed via scripts.
