### ISSUE TITLE
Misleading native spellchecker config directive

### ISSUE THREAD

**Issue by antonioprates** [frealgagu/archlinux.whatsapp-nativefier#17]
This line seems to have no effect:
```
--browserwindow-options '{ "webPreferences": { "spellcheck": true } }'
```
My system runs in english, but most of my chats to on WhatsApp are in portuguese, so the default spellchecker is an annoyance, I tried rebuilding the package with `"spellcheck": false`, and even removed that line entirely, just to figure out it would not make a difference.

On a little research I found this link reference:
https://github.com/nativefier/nativefier/blob/master/API.md

Appending these lines to the inject file seemed to do the trick to disable the spellchecker:
```
const electron = require('electron');
const request = {
  property: 'spellCheckerEnabled',
  propertyValue: false,
};
electron.ipcRenderer.send('session-interaction', request);
```

This is not really a bug, but the line with `browserwindow-options` on PKGBUILD is misleading since it does not take effect, made me spend some time to understand what was going on. Maybe removing that line and adding the proper code into the inject file would spare the time for other people.

**Comment by frealgagu** [comment]
It will be added in next bump up.
