### ISSUE TITLE
Safari Version is Out of Date

### ISSUE THREAD

**Issue by jay-tau** [frealgagu/archlinux.whatsapp-nativefier#19]
Safari version used appears out of date, and Whatsapp fails to load as shown in the below image.
![image](https://user-images.githubusercontent.com/95355656/173483383-7e4f9ef8-7f53-4ff3-9469-1784b54567c6.png)

**Comment by RickSlash84** [comment]
Same issue here in Majaro

**Comment by jereromero** [comment]
Same here... probably we need to wait for an update...

**Comment by RickSlash84** [comment]
Hopefully soon, this is the best standalone WhatsApp I've found so far. The others all have huge limitations.

**Comment by duberlyguarnizofuentesrivera** [comment]
Same error: Manjaro GNOME.

![Screenshot from 2022-06-14 22-51-41](https://user-images.githubusercontent.com/26314754/173733528-1ea7daee-60f9-4b20-92c5-a56ea22fcd30.png)

Link related, with manual FIX:
[https://aur.archlinux.org/packages/whatsapp-nativefier#comment-869668](url)

Requires editing the user-agent.

**Comment by muxina-credo** [comment]
Any news about this issue? Still having it on Manjaro 21.3.0.

**Comment by duberlyguarnizofuentesrivera** [comment]
> Any news about this issue? Still having it on Manjaro 21.3.0.

PR by LeackyPixel [here](https://github.com/frealgagu/archlinux.whatsapp-nativefier/pull/21#issue-1271998809) seems to fix it better than my own PR. No merge at sight, anyway.

**Comment by muxina-credo** [comment]
I'm still new to github. How in a project is able to merge alternative branches into master?

**Comment by duberlyguarnizofuentesrivera** [comment]
> I'm still new to github. How in a project is able to merge alternative branches into master?

That's to the owner of the repo, in this case @frealgagu. He/she/it decides what and when to merge.

**Comment by muxina-credo** [comment]
Thanks @duberlyguarnizofuentesrivera .

**Comment by frealgagu** [comment]
My apologies, I was AWOL, I'll be updating package soon.
