### ISSUE TITLE
Add System Tray Icon.

### ISSUE THREAD

**Issue by Shabinder** [frealgagu/archlinux.whatsapp-nativefier#2]
Possibility of adding A System tray Icon and minimize to it.
[Enhancement]

**Comment by frealgagu** [comment]
@Shabinder what DE are you using? the tray icon works perfectly in KDE

**Comment by Shabinder** [comment]
At the time I was using Manjaro Openbox.

**Comment by cemkaya-mpi** [comment]
I cannot see a tray icon either. I am using Gnome.

**Comment by Cantello** [comment]
I don't have a tray icon either (Manjaro Plasma). Anything special you need to do to get the tray icon - or better even: unread badge on the panel icon?

**Comment by cemkaya-mpi** [comment]
I'm not sure why, but the icon works for me now. Could it have something to do with electron version?

**Comment by frealgagu** [comment]
Do you have still this issue?

**Comment by cemkaya-mpi** [comment]
Seems to be fixed for me.

**Comment by frealgagu** [comment]
I'm closing this issue. Please open a new one if you have issues with tray icon.
