### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by bordam** [frealgagu/archlinux.whatsapp-nativefier#25]
Have you considered adding an option to enable minimized autostart?

**Comment by frealgagu** [comment]
You need to change the PKGBUILD and use start-in-tray option.

Change this:
```
build() {
  cd "${srcdir}"

  nativefier \
    --name "WhatsApp" \
    --icon "${pkgname}.png" \
    --width "800px" \
    --height "600px" \
    --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Chrome/107.0.5304.141 Safari/605.1.15" \
    --inject "${pkgname}-inject.js" \
    --verbose \
    --single-instance \
    --tray \
    "${url}"
}
```

for this:

```
build() {
  cd "${srcdir}"

  nativefier \
    --name "WhatsApp" \
    --icon "${pkgname}.png" \
    --width "800px" \
    --height "600px" \
    --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Chrome/107.0.5304.141 Safari/605.1.15" \
    --inject "${pkgname}-inject.js" \
    --verbose \
    --single-instance \
    --tray start-in-tray \
    "${url}"
}
```

Alternatively you can change file /opt/whatsapp-nativefier/resources/app/nativefier.json and change `"tray":"true"` for `"tray":"start-in-tray"`

For auto-start you need to add it to corresponding DesktopEnvironment auto-start section.

**Comment by bordam** [comment]
Thanks for the info, I created an AUR package to enable this behavior

https://aur.archlinux.org/packages/whatsapp-nativefier-autostart-tray-hook
