### ISSUE TITLE
Follow system theme preference

### ISSUE THREAD

**Issue by bordam** [frealgagu/archlinux.whatsapp-nativefier#26]
I.e. dark/light color scheme preference, for example on gnome

**Comment by frealgagu** [comment]
It's not possible to obtain the color scheme preference on execution time via nativefier, and even so we would need to change scripts to change color. The best way is to change it once installed via [Three dots]/Settings/Theme and it is stored in cache preferences, so next time you open the app it will have the theme unchanged.
