### ISSUE TITLE
Request for download location selection or set specific download location in the app

### ISSUE THREAD

**Issue by aayan-infosec** [frealgagu/archlinux.whatsapp-nativefier#28]
all the files and images go into my home directory then i have to move them. is there a possibility to add a function to specify location or prompt if i want to save in that location or somewhere else

**Comment by frealgagu** [comment]
You need to check if something like that is possible with https://github.com/nativefier/nativefier this way we could change PKGBUILD to create the app with that kind of customizations.

**Comment by frealgagu** [comment]
Maybe you can see this for reference:

https://github.com/nativefier/nativefier/blob/master/API.md#internal-browser-options

However, I'm not going to change the default download folder. If you want to use a different one you need to change the PKGBUILD in build time or change the configuration manually later.
