### ISSUE TITLE
Issue when Opening the App after closing it 

### ISSUE THREAD

**Issue by ramvikrams** [frealgagu/archlinux.whatsapp-nativefier#29]
I faced this issue regularly that whenever I made the app fullscreen and closed it, and  if I tried to open it, two windows come one of the fullscreen and a black window.
It only occurs with fullscreen, I have attached a video for your reference. 

[Screencast from 2023-01-20 23-51-18.webm](https://user-images.githubusercontent.com/106332857/213777042-b373190c-8bed-434d-92d6-ed33a7f913e4.webm)

**Comment by frealgagu** [comment]
Not sure if we can do something with this package, it seems something related to nativefier:

[https://github.com/nativefier/nativefier](https://github.com/nativefier/nativefier)
