### ISSUE TITLE
Update Google Chrome

### ISSUE THREAD

**Issue by m0rphtail** [frealgagu/archlinux.whatsapp-nativefier#3]
Doesn't work since today, getting this.

![Screenshot from 2021-03-09 17-40-25](https://user-images.githubusercontent.com/47940274/110468674-9b457100-80fe-11eb-8c68-ddbb709545cd.png)

**Comment by m0rphtail** [comment]
a reload solved it

**Comment by frealgagu** [comment]
Yes, that's something annoying, we have tried some approaches to avoid it, however tye script used to bypass the warning is not working anymore, there is a way to solve it changing the worker behavior and doing reloads. I think is the best workaround for now. More details about it are in the comments of the AUR package.

**Comment by frealgagu** [comment]
Is this issue still happening to you? At least it has been solved for me with the last changes I made (suggested in nativefier repo), please let me know and feel free to reopen the issue if it's not working with the latest version.

**Comment by m0rphtail** [comment]
so far no issues, updated it 3 days ago.

**Comment by m0rphtail** [comment]
got the update browser thing again today, and a couple days ago
changing the worker behavior and doing reloads worked
