### ISSUE TITLE
Problems with outdated browser, outdated nativefier etc

### ISSUE THREAD

**Issue by d-packs** [frealgagu/archlinux.whatsapp-nativefier#5]
There seems to be some work being done on this front to allow whatsapp to run in nativefier without issues. 
Are the fixes and flags provided in this thread being used?
https://github.com/nativefier/nativefier/issues/1112

**Comment by nix-enthusiast** [comment]
Same issue here.
Old chrome browser.

**Comment by frealgagu** [comment]
Same as #3
