### ISSUE TITLE
Injection code not working anymore

### ISSUE THREAD

**Issue by nielstron** [frealgagu/archlinux.whatsapp-nativefier#7]
The injection code to make whatsapp work in a nativefier app recently stopped working for me.

However, in case anyone else has the same issue, here is my workaround/new injection js (developed in https://github.com/nativefier/nativefier/issues/719):
```js
function recheck () {
    navigator.serviceWorker.getRegistrations().then((registrations) => {
        for(registration of registrations){
             registration.unregister();
        }
        if (document.querySelector("body[class='page-version']")) {
            console.log("reload");
            document.location.reload();
         }
    });
    setTimeout(recheck, 5000); // callback
}
recheck();

```
(already in https://github.com/nielstron/ubuntu.whatsapp-nativefier)

It might be a good idea to include it in future releases of the package if more people have this issue.

**Comment by NicolasWebDev** [comment]
@nielstron , I am not totally clear on how we should inject that code? In the other thread there was the mention of a file in which to inject the code but it never worked for me.

**Comment by nielstron** [comment]
In order to make use of the alternative injection code, replace the code in "whatsapp-nativefier-inject.js" with it and rebuild the app locally.

**Comment by NicolasWebDev** [comment]
The injection code worked perfectly, thank you for the fix @nielstron .

**Comment by Nowaker** [comment]
I rebuilt the package with the new code and it didn't work for me. I'm still stuck on the error message.

**Comment by Nowaker** [comment]
I've spotted the problem in Nativier-generated preload.js:

```js
function injectScripts() {
    const needToInject = fs.existsSync(exports.INJECT_DIR);
    if (!needToInject) {
        return;
    }
    // Dynamically require scripts
    try {
        const jsFiles = fs
            .readdirSync(exports.INJECT_DIR, { withFileTypes: true })
            .filter((injectFile) => injectFile.isFile() && injectFile.name.endsWith('.js'))
            .map((jsFileStat) => path.join('..', 'inject', jsFileStat.name));
        for (const jsFile of jsFiles) {
            log.debug('Injecting JS file', jsFile);  // <------------- PROBLEM HERE
            require(jsFile);
        }
    }
    catch (err) {
        log.error('Error encoutered injecting JS files', err);
   }
```

`log` is not defined, so the code never goes to `require(jsFile)`. Instead all you get is:
```
VM1776 preload.js:84 Uncaught ReferenceError: log is not defined
    at injectScripts (VM1776 preload.js:84)
    at HTMLDocument.<anonymous> (VM1776 preload.js:29)
```

Therefore, it's not a problem with our injection code. It's a problem with the code that is supposed to execute our injection code.

How to fix it temporarily:

1. Open the dev tools (CTRL+SHIFT+I)
2. Go to Console.
3. Click on the `VM843_preload.js:84` to go to `preload.js` file.
4. Place a breakpoint on line 79: `log.debug('Injecting JS file', jsFile);` by clicking on the line number. A blue arrow (kinda) should show up.
5. Go to Console and execute `document.location = 'https://web.whatsapp.com/'`
6. The code should hit a breakpoint. Your dev tools automatically went to the Sources tab and breakpoint is highlighted. 
![image](https://user-images.githubusercontent.com/611746/135181062-9dcdd757-f69e-4410-8f1a-7aed22cba0c1.png)
7. Execute `require(jsFile);` manually in the Console.
8. Press F8 or the continue button that's shown on the page. 
![image](https://user-images.githubusercontent.com/611746/135181024-9392500e-e9c3-4862-b500-ccade0aecf6d.png)
9. Press F9 once again.
8. ???
9. PROFIT!

**Comment by hmlendea** [comment]
> How to fix it temporarily:
> 
>     1. Open the dev tools (CTRL+SHIFT+I)
> 
>     2. Go to Console.
> 
>     3. Click on the `VM843_preload.js:84` to go to `preload.js` file.
> 
>     4. Place a breakpoint on line 79: `log.debug('Injecting JS file', jsFile);` by clicking on the line number. A blue arrow (kinda) should show up.
> 
>     5. Go to Console and execute `document.location = 'https://web.whatsapp.com/'`
> 
>     6. The code should hit a breakpoint. Your dev tools automatically went to the Sources tab and breakpoint is highlighted.
>        ![image](https://user-images.githubusercontent.com/611746/135181062-9dcdd757-f69e-4410-8f1a-7aed22cba0c1.png)
> 
>     7. Execute `require(jsFile);` manually in the Console.
> 
>     8. Press F8 or the continue button that's shown on the page.
>        ![image](https://user-images.githubusercontent.com/611746/135181024-9392500e-e9c3-4862-b500-ccade0aecf6d.png)
> 
>     9. Press F9 once again.
> 
>     10. ???
> 
>     11. PROFIT!
A more permanent workaround would be to edit `/opt/whatsapp-nativefier/resources/app/lib/preload.js` and add `require(jsFile);` at line 79 right before the `log.debug(...)` call

**Comment by Nowaker** [comment]
Yay, so preload.js exists in the filesystem! I thought it was baked into the Electron binary and didn't even check with pacman -Ql. Cool. In this case we can not only fix it temporarily on our computers, but patch it in PKGBUILD! I'll have a PR coming later today.

**Comment by hmlendea** [comment]
If it could be fixed in the PKGBUILD that would be awesome!

**Comment by Nowaker** [comment]
@hmlendea See the PR above. Our PKGBUILD is actually what broke things.

**Comment by frealgagu** [comment]
This line was added in the past to allow verification of preload in runtime. I'll remove it and see what happens.
