### ISSUE TITLE
App shows a blank screen if network is offline

### ISSUE THREAD

**Issue by PolpOnline** [frealgagu/archlinux.whatsapp-nativefier#9]
Hi, I had this problem since I installed this package.
Basically, I set up the app to autostart with the KDE autostarting manager, the problem is that my network goes online only after I log in and this causes the app to not reach the network in time and fail. A possible solution would be to inject a script that checks if the network is online periodically and reload the page if it is.
Thanks

**Comment by frealgagu** [comment]
This seems to be an electron issue, not sure if a script could help. If you want to try and it works please open a pull request and I'll be glad to accept it.
